Controllers/BikeController.cs
using AutoMapper;
using Bikes.Controllers.Resources;
using Bikes.Data;
using Bikes.Models;
using Bikes.Models.ViewModels;
using Bikes.RoleMembers;
using cloudscribe.Pagination.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Bikes.Controllers
{
	[Authorize(Roles = Roles.Admin+","+Roles.Executive)]
	public class BikeController : Controller
	{
		private readonly ApplicationDbContext _db;
		private readonly IWebHostEnvironment _webhostEnv;

		[BindProperty]
		public BikeViewModel BikeVM { get; set; }

		public BikeController(ApplicationDbContext db, IWebHostEnvironment webhostEnv)
		{
			_db = db;
			_webhostEnv = webhostEnv;
			BikeVM = new BikeViewModel()
			{
				Makes = _db.Makes.ToList(),
				Models = _db.Models.ToList(),  //changed to list of models
				Bike = new Models.Bike()
			};
		}

		[AllowAnonymous]
		public IActionResult Index(string searchString, string sortOrder, int pageNumber = 1, int pageSize = 2)
		{
			ViewBag.CurrentSortOrder = sortOrder;
			ViewBag.CurrentFilter = searchString;
			ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "Price_desc": "";
			int ExcludeRecords = (pageSize * pageNumber) - pageSize;
			var bikes = from b in _db.Bikes.Include(m => m.Make).Include(m => m.Model)
						select b;
			var bikeCount = bikes.Count();
			if (!String.IsNullOrEmpty(searchString))
			{
				bikes = bikes.Where(b => b.Make.Name.Contains(searchString));
				bikeCount = bikes.Count();
			}
			//Sorting Logic
			switch (sortOrder)
			{
				case "Price_desc":
					bikes = bikes.OrderByDescending(b => b.Price);
					break;
				default:
					bikes = bikes.OrderBy(b => b.Price);
					break;
			}
			bikes = bikes
				.Skip(ExcludeRecords)
				.Take(pageSize);
			var result = new PagedResult<Bike>
			{
				Data = bikes.AsNoTracking().ToList(),
				TotalItems = bikeCount,
				PageNumber = pageNumber,
				PageSize = pageSize
			};
			return View(result);
		}
		
		[HttpGet]
		public IActionResult Create()
		{
			return View(BikeVM);
		}

		[HttpPost, ActionName("Create")]
		//	[ValidateAntiForgeryToken]
		public IActionResult CreatePost()
		{
			if (!ModelState.IsValid)
			{
				BikeVM.Makes = _db.Makes.ToList();
				BikeVM.Models = _db.Models.ToList();
				return View(BikeVM);
			}
			_db.Add(BikeVM.Bike);			
			_db.SaveChanges();
			UploadImage();
			return RedirectToAction(nameof(Index));
		}

		private void UploadImage()
		{
			//Save bike logic
			//Get bike id we have saved in database
			var BikeID = BikeVM.Bike.Id;
			//Get the www root folder to save the file in server
			string wwwRootPath = _webhostEnv.WebRootPath;
			//Get the uploaded files
			var files = HttpContext.Request.Form.Files;
			//Get the reference of dbset for the bike we just saved to the database
			var SavedBike = _db.Bikes.Find(BikeID);
			//upload the files on server and save the image path if user have uploaded any file.
			if (files.Count != 0)
			{
				var imagePath = @"images\bike";
				var Extension = Path.GetExtension(files[0].FileName);
				var RelativeImagePath = imagePath + BikeID + Extension;
				var AbsImagePath = Path.Combine(wwwRootPath, RelativeImagePath);
				//upload the file on server
				using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
				{
					files[0].CopyTo(fileStream);
				}
				//set the image path on the database
				SavedBike.ImagePath = RelativeImagePath;
				_db.SaveChanges();
			}
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			BikeVM.Bike = _db.Bikes.SingleOrDefault(m => m.Id == id);
			//filter the models associated with the make
			BikeVM.Models = _db.Models.Where(m => m.MakeId == BikeVM.Bike.MakeId);
			if (BikeVM.Bike == null)
			{
				return NotFound();
			}
			return View(BikeVM);
		}

		[HttpPost, ActionName("Edit")]
		public IActionResult EditPost()
		{
			if (!ModelState.IsValid)
			{
				BikeVM.Makes = _db.Makes.ToList();
				BikeVM.Models = _db.Models.ToList();
				return View(BikeVM);
			}
			_db.Update(BikeVM.Bike);			
			_db.SaveChanges();
			UploadImage();

			return RedirectToAction(nameof(Index));
		}

		public IActionResult Delete(int id)
		{
			Bike bike = _db.Bikes.Find(id);
			if (bike == null)
			{
				return NotFound();
			}
			_db.Bikes.Remove(bike);
			_db.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		[AllowAnonymous]
		public IActionResult Details(int id)
		{
			BikeVM.Bike = _db.Bikes.SingleOrDefault(m => m.Id == id);
			if (BikeVM.Bike == null)
			{
				return NotFound();
			}
			return View(BikeVM);
		}


	}
}

Controllers/MakeController.cs
using Bikes.Data;
using Bikes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bikes.Controllers
{
	[Authorize(Roles = "Admin,Executive")]
	public class MakeController : Controller
	{
		private readonly ApplicationDbContext _db;

		public MakeController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			var AllMakes = _db.Makes.ToList();
			return View(AllMakes);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Make make)
		{
			if (ModelState.IsValid)
			{
				_db.Add(make);
				_db.SaveChanges();
				return RedirectToAction(nameof(Index));
			}
			return View(make);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
			var make = _db.Makes.Find(id);
			if (make == null)
			{
				return NotFound();
			}
			_db.Remove(make);
			_db.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var make = _db.Makes.Find(id);
			if (make == null)
			{
				return NotFound();
			}
			return View(make);
		}

		[HttpPost]
		public IActionResult Edit(Make make)
		{
			if (ModelState.IsValid)
			{
				_db.Update(make);
				_db.SaveChanges();
				return RedirectToAction(nameof(Index));
			}
			return View(make);
		}
	}
}

Controllers/ModelController.cs
using AutoMapper;
using Bikes.Controllers.Resources;
using Bikes.Data;
using Bikes.Models;
using Bikes.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bikes.Controllers
{
	[Authorize(Roles = "Admin,Executive")]
	public class ModelController : Controller
	{
		private readonly ApplicationDbContext _db;
		private readonly IMapper _mapper;

		[BindProperty]
		public ModelViewModel ModelVM { get; set; }

		public ModelController(ApplicationDbContext db, IMapper mapper)
		{
			_db = db;
			_mapper = mapper;
			ModelVM = new ModelViewModel()
			{
				Makes = _db.Makes.ToList(),
				Model = new Models.Model()
			};
		}

		public IActionResult Index()
		{
			var model = _db.Models.Include(m => m.Make);
			return View(model);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View(ModelVM);
		}

		[HttpPost, ActionName("Create")]
	//	[ValidateAntiForgeryToken]
		public IActionResult CreatePost()
		{
			if (!ModelState.IsValid)
			{
				return View(ModelVM);
			}
			_db.Add(ModelVM.Model);
			_db.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			ModelVM.Model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
			if (ModelVM.Model == null)
			{
				return NotFound();
			}
			return View(ModelVM);
		}

		[HttpPost, ActionName("Edit")]
		public IActionResult EditPost()
		{
			if (!ModelState.IsValid)
			{
				return View(ModelVM);
			}
			_db.Update(ModelVM.Model);
			_db.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Delete(int id)
		{
			Model model = _db.Models.Find(id);
			if (model == null)
			{
				return NotFound();
			}
			_db.Models.Remove(model);
			_db.SaveChanges();
			return RedirectToAction(nameof(Index));
		}

		[AllowAnonymous]
		[HttpGet("api/models/{MakeID}")]
		public IEnumerable<Model> Models(int MakeID)
		{
			return _db.Models.ToList()
				.Where(m => m.MakeId == MakeID);
		}

		[AllowAnonymous]
		[HttpGet("api/models")]
		public IEnumerable<ModelResources> Models()
		{
			var model = _db.Models.ToList();
			var modelResources = _mapper.Map<List<Model>, List<ModelResources>>(model);
			return modelResources;
		}
	}
}

Views/Shared/_Layout.cshtml
@using Bikes.RoleMembers
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Bikes</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			@*fixed-top*@
			<a class="navbar-brand" asp-controller="Bike" asp-action="Index"><i class="fas fa-bicycle"></i></a>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" asp-controller="Bike" asp-action="Index">Home</a>
					</li>
					@if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
					{
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Masters
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a>
								<a class="dropdown-item" asp-controller="Model" asp-action="Index">Models</a>
								<a class="dropdown-item" asp-controller="Bike" asp-action="Index">Bikes</a>
								@if (User.IsInRole(Roles.Admin))
								{
									<a class="dropdown-item" id="register" asp-area="Identity" asp-page="/Account/Register">Add User</a>
								}
							</div>
						</li>
					}
				</ul>
			</div>
			<partial name="_LoginPartial" />
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			<br /><br /><br />
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - Bikes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/font-awesome/js/all.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber=Model.PageNumber
		  cs-paging-totalitems=Model.TotalItems
		  cs-paging-pagesize=Model.PageSize
		  cs-pagenumber-param="pageNumber"
		  asp-route-searchString ="@ViewBag.CurrentFilter"
		  asp-route-sortOrder="@ViewBag.CurrentSortOrder"
		  asp-controller=@ViewData["Controller"]
		  asp-action=@ViewData["Action"]
		  cs-pager-li-current-class="page-item-active"
		  cs-pager-li-other-class="page-item"
		  cs-pager-li-non-active-class="page-item-disabled"
		  cs-pager-link-current-class="page-link"
		  cs-pager-link-other-class="page-link">
</cs-pager>

Views/Shared/_TableButtonPartial.cshtml
@model int
<td class="text-right">
	<div class="btn-group" role="group">
		<a type="submit" class="btn btn-primary" asp-action="Edit" asp-route-id="@Model"><i class="far fa-edit"></i></a>
		<form action="Delete" method="post">
			<Button onclick="if (!confirm('Are you sure you want to delete this item')){ return false}" type="submit" class="btn btn-danger rounded-0" asp-action="Delete" asp-route-id="@Model" value="Delete"><i class="far fa-trash-alt"></i></Button>
		</form>
	</div>
</td>